name: Git.StepBroBD.com
host: Git.StepBroBD.com
port: 23231

anon-access: no-access
allow-keyless: false

users:
  - name: StepBroBD
    admin: true
    public-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICVktHp6yjTknysVbU24K014tFKCIIM3/rWqZV591NRn Yifei@Yifeis-MacBook-Pro.local
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCd98YeQmY5HOvC7q/0O+f6t1pSw5Tin1JdaFCVd9DckOZBLK4uIJJyvTZCKN1vdPMPh6CmTeOyjmCURQkHfkhLD3u9JFX2GHJ7Wa2O6/JQ6ikXCRWYirMMdKySbDANcRERedt0Z7/sgdJpkFHybtapgyvEJVcqsEqjfycgVDOQ4377t2I//Zk+QLmDEjpmubIILF/yLWH8hmr3muG9Brp3WbRnqI1+WocigmZXK21vTTCG3RgAR3CoAspxIad3S5yTJE++rqewyAz4CdnG8J1GCBjR49QuQo+4Q8R7u+8fzlFVhESEzesVatdz+gx0O99ZO/P4lNe3Nc3Oep19dUDf7IMiNIQhNraXxzU7aEZKj7SaJa6H5rw3WIYk62NKIcSHrLyreDhqKhczkGN9WnWmcU6fWbANVC+OfaF1E6aXEkSBnpK29FeVlE/IF4QndbFI/pG1sGqgFzo7kSy9N/UnvfFdKbupxjLu3BXK8Jn2NAD2dZTVaU1WvWdtlz8o0QM= StepBroBD@ams.server.stepbrobd.com
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQD1WafsXveyMKUgxHR1ETJP2tx/5XdPxMKoooL9bwzo145nrkE0o6emF5lA6e5yqY4YjkExEv4jdOBkKwC5ycUphRJh8NZUnRixBF7eJvHi5M9KbhUqfmS/C7Htk9ASPetTd9GkbR1vwHyNFF0x9TKbZXItWsZG+raBqlABhSN4epUR6wqvJnYeRoXO0TXb8hg1BBNRIIJQ2ikk4UmSkjnu0HT2/W6oLkc2MDsvOYn9aj8kR9/JV0jPWz44zh8p7B8jBGJEQEkKZOrmRnXHEkzCKknXTjDB4tegrjqJ7fJNVR5kfZqMk5NRLBIqrf2XtzxBl4KIXovueL7KinNo0B2uOkj1jly+Fe5mWLBRcnrZYv+A0vvQbONIGYfMQ+UaJWxvSFlY/y6aOwALMgC5dYlBSlo4w4sBNwSvC6Th7cmnBYA5EhWOSyEW2M42X9yGLjVQgWPulRuS03LApEOY25pBxss8jSz4LMkZXfiaURv0Iq+DSB6Unj5T8rHosRFPBBk= StepBroBD@jfk.server.stepbrobd.com
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDKSS6NjDOzTmsv/sbv3Fs9nVRFA2lDMT61T6YzJrHhKtmhjpAhUd+dPXhcr7oiE2pw+6bK96pHZrdzOPRK6qUluowSdVwknimpLZHLiP2mDFldsY1eBkTXdK9kZLGbHt+dfqwdPgV1W//8dJ2loGWDT6zJkwtDMTnsRoLRtNZCPR4zW8uhAtQnIM3rxgBiz1Lb9tkQqsSUpYN6693JsT8r2ieJOwOd05i2Jh+Jpgme/RIUn6dN1eo1Ye3eM52/HF4N4wPoDpzSOjkh0XFlcUtYkXm9dzg8/bQX68oP9JcmFGLR7cIE/l8nThILke3/8zjKjG6EBUBdhDAKhBefbjzoTjCutTdwN2kJwEOMHJnMR/p/rmVvjFMzhdIakipBQo31WKEpzgll7oWpBbajMKTrz/RDHY1kqrGRc7igxB5CgQVlMMg/+jbDlQPwWTrIxRIKoECml3DRrEYLeb7XWi1gzJxOANZkCcZEJCeUrGYUqjAnuU+wsPB3cLdmXgH+288= StepBroBD@nrt.server.stepbrobd.com
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCddJB9clbTf07JAQrNvktwf1kDQ64MWQf7cuBULcHxAupiObewKV1G72zQevGuwxqzOmCW87rJIbJvF25rUQkg9Tw/3vP8kC58a6O5gnhqQLSkUSKlUs51tNbqRI17/DP6yy+jDkpGSQKaskTDetIpq86w9RLfRcRvuf++JAV/qDjay0SXwCL6+0w3QJQA/oBkycCboE4nBwx5J3ajyakqgOA01WhWanrBc8ioOr3QjBEbrzpizXtLC+5mhzPeDvOHnxIX61+/FHnqKnMoOLrthrOnVExMFUXwO8CTAyi2okN8JWlSIGIXH406d+iClP/a2OOFQe7QKl8hJDziMv6t55hS1R3SW4QHNctD21fLeYegQhdF5mXEvEDFbJ+5Y2GNdpaz04o0zWjFUgTekhzQMQVGJqdZyb9MZMSG/SE5IabEUoGSIaoEqiqgLU48PMQY3u49uBJ6Mx7BZHlRrALr293u2m4eKxSJVt9PMW9htqM0FZDKivtl2rjq1QrSy+E= u1298569@lab1-17.eng.utah.edu

repos:
  - name: Configurations
    repo: config
    private: true
    note: "Server configurations"
    readme: README.md

  - name: Deployment + Configurations
    repo: com-stepbrobd-git-config
    private: true
    note: "Server configurations"
    readme: README.md

  - name: StepBroBD.com
    repo: com-stepbrobd-web
    private: true
    note: "https://StepBroBD.com"
    readme: README.md

  - name: Yifei.md
    repo: com-stepbrobd-yifei
    private: true
    note: "https://Yifei.md"
    readme: README.md

  - name: University of Utah CS 6450
    repo: edu-utah-cs6450
    private: true
    note: "CS 6450 Fall 2022 @ The University of Utah"
    readme: README.md

  - name: University of Utah CS 5340
    repo: edu-utah-cs5340
    private: true
    note: "CS 5340 Fall 2022 @ The University of Utah"
    readme: README.md

  - name: University of Utah CS 4480
    repo: edu-utah-cs4480
    private: true
    note: "CS 4480 Spring 2022 @ The University of Utah"
    readme: README.md

  - name: University of Utah CS 4440
    repo: edu-utah-cs4440
    private: true
    note: "CS 4440 Spring 2022 @ The University of Utah"
    readme: README.md

  - name: University of Utah CS 4400
    repo: edu-utah-cs4400
    private: true
    note: "CS 4400 Fall 2021 @ The University of Utah"
    readme: README.md

  - name: University of Utah CS 4150
    repo: edu-utah-cs4150
    private: true
    note: "CS 4150 Spring 2022 @ The University of Utah"
    readme: README.md

  - name: University of Utah CS 3505
    repo: edu-utah-cs3505
    private: true
    note: "CS 3505 Fall 2021 @ The University of Utah"
    readme: README.md

  - name: University of Utah CS 3500 Part 2
    repo: edu-utah-cs3500-2
    private: true
    note: "CS 3500 Spring 2021 @ The University of Utah"
    readme: README.md

  - name: University of Utah CS 3500 Part 1
    repo: edu-utah-cs3500-1
    private: true
    note: "CS 3500 Spring 2021 @ The University of Utah"
    readme: README.md

  - name: University of Utah CS 2420
    repo: edu-utah-cs2420
    private: true
    note: "CS 2420 Fall 2020 @ The University of Utah"
    readme: README.md

  - name: University of Utah CS 1410
    repo: edu-utah-cs1410
    private: true
    note: "CS 1410 Spring 2020 @ The University of Utah"
    readme: README.md
